apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: falcon-40b-instruct
  namespace: kserve-demo
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/autoscalerClass: external
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-multinode-runtime
      storageUri: pvc://pvc-falcon-40b-instruct/falcon-40b-instruct/snapshots/ecb78d97ac356d098e79f0db222c9ce7c5d9ee5f/
    workerSpec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      pipelineParallelSize: 2
      tensorParallelSize: 1
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "4"
          memory: "24Gi"
          nvidia.com/gpu: "1"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"