apiVersion: v1
kind: Pod
metadata:
  name: download-falcon-40b
  labels:
    name: download-falcon-40b
spec:
  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: pvc-falcon-40b-instruct
  restartPolicy: Never
  initContainers:
    - name: fix-volume-permissions
      image: quay.io/quay/busybox@sha256:92f3298bf80a1ba949140d77987f5de081f010337880cd771f7e7fc928f8c74d
      command: ["sh"]
      args: ["-c", "mkdir -p /mnt/models/$(MODEL_PATH) && chmod -R 777 /mnt/models"] 
      volumeMounts:
        - mountPath: "/mnt/models/"
          name: model-volume
      env:
        - name: MODEL_PATH
          value: falcon-40b-instruct 
  containers:
    - resources:
        requests:
          memory: 10Gi
      name: download-model
      imagePullPolicy: IfNotPresent
      image: quay.io/opendatahub/kserve-storage-initializer:v0.14 
      args:
        - 's3://$(BUCKET_NAME)/$(MODEL_PATH)/'
        - /mnt/models/$(MODEL_PATH)
      env:
        - name: AWS_ACCESS_KEY_ID
          value: 
        - name: AWS_SECRET_ACCESS_KEY
          value: 
        - name: BUCKET_NAME
          value: rhoai-llm-model
        - name: MODEL_PATH
          value: falcon-40b-instruct 
        - name: S3_USE_HTTPS
          value: "1"
        - name: AWS_ENDPOINT_URL
          value: https://s3.us-east-2.amazonaws.com 
        - name: awsAnonymousCredential
          value: 'false'
        - name: AWS_DEFAULT_REGION
          value: us-east-2 
        - name: S3_VERIFY_SSL
          value: 'true' 
      volumeMounts:
        - mountPath: "/mnt/models/"
          name: model-volume