apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-falcon-40b-instruct
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs