apiVersion: v1
kind: Service
metadata:
  name: falcon-40b-instruct-service
  namespace: kserve-demo
spec:
  selector:
    app: isvc.falcon-40b-instruct-predictor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
